version: "3.8"

services:
  database:
    image: postgres:14.1-alpine
    container_name: todos-pg-database
    restart: always
    ports:
      - ${PG_PORT}:${PG_PORT}
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=dotosdb
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  app-dev:
    build:
      dockerfile: ./Dockerfile
      context: .
    profiles: ["dev"]
    container_name: node-todo-api
    ports:
      - 3333:3333
    volumes:
      - .:/app
    network_mode: host

volumes:
  pgdata:
