version: "3.9"

services:
  database:
    image: postgres
    container_name: todos-pg-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=todosdb
    volumes:
      - pgdata:/data/postgress
    network_mode: host
  app:
    build: .
    container_name: node-todo-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    network_mode: host

volumes:
  pgdata:
