version: "3.8"

services:
  database:
    image: postgres:14.1-alpine
    container_name: todos-pg-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=todosdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: host

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  app:
    build: .
    container_name: node-todo-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    network_mode: host

volumes:
  pgdata:
