version: "3.8"

services:
  database:
    image: postgres:14.1-alpine
    container_name: todos-pg-database
    restart: always
    ports:
      - 5984:5984
    environment:
      - POSTGRES_USER=dotosdb
      - POSTGRES_PASSWORD=E1A731033BC08FDB1CC0BFCDD
      - POSTGRES_DB=dotosdb
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  app:
    build: .
    container_name: node-todo-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    network_mode: host

volumes:
  pgdata:
